### ISSUE TITLE
Type from assembly 'AutoMapper.Proxies tried to override method 'add_PropertyChanged' but does not implement or inherit that method.

### ISSUE THREAD

**Issue by BradyLiles** [AutoMapper/AutoMapper#2250]
### Expected behavior

In version 6.0.2 my Linq2Sql ORM maps just fine without throwing any errors

### Actual behavior

**What I'm doing**

I am receiving this error when upgrading from 6.0.2 to 6.1.0
I am mapping a database structure using LINQ2SQL ORM to a public facing DTO's for an OData API.

I am mapping 2 DTO's together and that could possibly be the issue knowing the DTO does not have the method "add_PropertyChanged" in the DTO.

**Error I'm Receiving**

`Type 'ProxyMemberTableDTO_FamilyTableDTO<MyNamespace_Version=1.0.0.0_Culture=neutral_PublicKeyToken=null>' from assembly 'AutoMapper.Proxies, Version=0.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' tried to override method 'add_PropertyChanged' but does not implement or inherit that method.`

**POSSIBLE FIX**

It seems that in the ProxyGenerator Class when it executes the following:
```
typeBuilder.DefineMethodOverride(addPropertyChangedMethod,
	iNotifyPropertyChanged_PropertyChanged.AddMethod);
typeBuilder.DefineMethodOverride(removePropertyChangedMethod,
	iNotifyPropertyChanged_PropertyChanged.RemoveMethod);
```

- https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Execution/ProxyGenerator.cs#L100

The code does not check if the current method even exists in the original context. I don't have an environment set up ( Why I'm not just doing a PR )

I feel like an appropriate fix would be to do a `DefineMethod` if the property does not exist previously and a `DefineMethodOverride` if the method already does exist in the original class.

Something along the lines of:
```
if ( /* addPropertyChangedMethod exists */ ) {
typeBuilder.DefineMethodOverride(addPropertyChangedMethod,
	iNotifyPropertyChanged_PropertyChanged.AddMethod);
} else {
typeBuilder.DefineMethod(addPropertyChangedMethod,
	iNotifyPropertyChanged_PropertyChanged.AddMethod);
}

if ( /* removePropertyChangedMethod exists */ ) {
typeBuilder.DefineMethodOverride(removePropertyChangedMethod,
	iNotifyPropertyChanged_PropertyChanged.RemoveMethod);
} else {
typeBuilder.DefineMethod(removePropertyChangedMethod,
	iNotifyPropertyChanged_PropertyChanged.RemoveMethod);
}
```

**Comment by BradyLiles** [comment]
If any contributors have further knowledge of why this might be occurring and are even able to provide a some insight of how to get a fixed solution for this is appreciated!

**Comment by lbargaoanu** [comment]
If you're absolutely sure this used to work and is broken now, it should be easy to find the offending commit in history.

**Comment by BradyLiles** [comment]
I'll do my due diligence and just do process of elimination and attempt to find the specific change set. I'm still unsure if the idea is still valid where it should only override if it currently existed in the class.

**Comment by TylerCarlson1** [comment]
Are you happening to be using 'CreateMissingTypeMaps=true;' by any chance?

**Comment by lbargaoanu** [comment]
Waiting for a fix or a repro.

**Comment by BradyLiles** [comment]
I apologize I had to step away from this for this week. But I should be investigating it again here soon. 
I was having serious difficulties making a debug build of AutoMapper so I could step through the code... I could not get my .Net Core Web App to reference the debug build of the dll because it said it would only take a dll from NuGet. So I tried to build to NuGet without much luck and my solution is in VS2015 and currently can't easily be migrated over to VS2017. I tried looking for a PDB file and getting that to work. 

It kind of became a giant hassle just to get a build I could debug; and still have yet to even be able to step through the code successfully.. -_-

If you have any pointers on how to create a local NuGet package or a way I can step through the code it would be appreciated!!! xD

**Comment by lbargaoanu** [comment]
@jbogard takes care of these things, but I think our package has symbols and you should be able to debug it the same way as you debug the .NET framework for example.

**Comment by jbogard** [comment]
Yep, I upload symbol packages to the symbol server

**Comment by BradyLiles** [comment]
Awesome, I'll take another look.
Thanks @jbogard  @lbargaoanu

**Comment by BradyLiles** [comment]
@jbogard Where is the symbol server?
I previously thought it was:
https://www.symbolsource.org/Public/Metadata/NuGet/Project/AutoMapper

But the most recent symbol version is 4.0.4

**Comment by BradyLiles** [comment]
https://ci.appveyor.com/project/jbogard/automapper/build/1306/artifacts
Is that where it would be? xD

**Comment by jbogard** [comment]
Nope, it's https://nuget.smbsrc.net/ now.

**Comment by MrZander** [comment]
I'm getting this exact error.  Any idea what caused it @BradyLiles ?
